"use client";

import Link from "next/link";
import { NoteGrid } from "@/components/notes/note-card";
import { useNotesCache } from "@/components/notes/notes-cache-provider";

export default function DashboardPage() {
  const { notes, loading, error, reload } = useNotesCache("recent");
  return <div><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="text-sm text-zinc-500">Your personal knowledge space</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">Good morning</h1><p className="mt-2 max-w-xl text-sm text-zinc-500">Capture ideas, useful information, and things you want to find again.</p></div><Link href="/notes/new" className="inline-flex w-fit items-center gap-2 rounded-lg bg-zinc-900 px-4 py-2.5 text-sm font-medium text-white shadow-sm transition hover:bg-zinc-700 dark:bg-zinc-100 dark:text-zinc-900 dark:hover:bg-white"><span>+</span> New note</Link></div><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><QuickAction href="/notes/new?type=GENERAL" label="New note" hint="Start writing" /><QuickAction href="/notes/new?type=PROMPT" label="New prompt" hint="Save a reusable prompt" /><QuickAction href="/notes/new?type=IDEA" label="New idea" hint="Capture a thought" /><QuickAction href="/notes/new?type=CODE" label="New code" hint="Keep a useful snippet" /></div><section className="mt-10"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-lg font-semibold">Recently used</h2><p className="mt-1 text-sm text-zinc-500">Notes you opened most recently</p></div><Link href="/recent" className="text-sm text-zinc-500 underline underline-offset-4">View all</Link></div>{loading ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><div className="h-44 animate-pulse rounded-xl bg-zinc-200 dark:bg-zinc-800" /><div className="h-44 animate-pulse rounded-xl bg-zinc-200 dark:bg-zinc-800" /><div className="h-44 animate-pulse rounded-xl bg-zinc-200 dark:bg-zinc-800" /></div> : error ? <div className="rounded-xl border border-red-200 bg-red-50 p-8 text-center text-sm text-red-700 dark:border-red-900 dark:bg-red-950/30 dark:text-red-300">Unable to load recent notes. <button onClick={reload} className="underline">Try again</button></div> : <NoteGrid notes={notes} />}</section></div>;
}

function QuickAction({ href, label, hint }: { href: string; label: string; hint: string }) { return <Link href={href} className="workspace-panel rounded-xl p-4 transition hover:-translate-y-0.5 hover:border-zinc-400 hover:shadow-sm dark:hover:border-zinc-600"><span className="text-sm font-medium">{label}</span><span className="mt-1 block text-xs text-zinc-500">{hint}</span></Link>; }
